### ISSUE TITLE
unable to compile with Angular 8.3

### ISSUE THREAD

**Issue by dimpyvirk** [nickcam/FlareClusterLayer#65]
My application is using 
angular 8.3
@types/arcgis-js-api": "^4.15.0",
@arcgis/webpack-plugin": "4.15.0",
dojo-typings": "^1.11.9

import asd = require('esri/core/accessorSupport/decorators');

when I try to compile I am getting the following error

74 line means --> @asd.subclass("FlareClusterLayer")

ERROR in app/map/flare-cluster-layer.ts(74,2): Error during template compile of 'FlareClusterLayer'
  Could not resolve esri/core/accessorSupport/decorators relative to [object Object]..

**Comment by nickcam** [comment]
Hi @dimpyvirk - I haven't used the @arcgis/webpack-plugin before, so not sure how that works. I have used this project in an angular project - it was a while ago though, v4 I think. 

Check out the [esri-loader](https://github.com/Esri/esri-loader) package. It has examples on how to load arcgis js api into Angular apps. If you use that you can just include the compiled javascript file as another module. There's an example in the readme for doing that - [https://github.com/Esri/esri-loader#configuring-dojo](https://github.com/Esri/esri-loader#configuring-dojo).
